### ISSUE TITLE
Get Exception in thread "main" java.lang.ClassCastException by running jasperstarter in console

### ISSUE THREAD

**Issue by legendgod** [cossou/JasperPHP#120]
My Java version:

> openjdk 11.0.6 2020-01-14
> OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
> OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

My Jasper version:

> JasperStarter 3.0.0 Rev e5bdd94 (jasperstarter-3.0.0)
>  - JasperReports: 6.0.4

I am using Laravel with Jasperphp. In one of the webpage I am trying to generate a pdf report but fail with php error. In order to troubleshoot I called below command in console:

`/var/www/mysite/vendor/cossou/jasperphp/src/JasperStarter/bin/jasperstarter process /var/www/mysite/vendor/cossou/jasperphp/src/JasperStarter/examples/charactersetTest.jrxml -o "/var/www/mysite/vendor/cossou/jasperphp/src/JasperStarter/examples" -f pdf -t mysql -u root -H localhost -n mydatabase`

Then I got below error:

> Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
>         at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:72)
>         at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:62)
>         at de.cenote.tools.classpath.ApplicationClasspath.addJars(ApplicationClasspath.java:127)
>         at de.cenote.tools.classpath.ApplicationClasspath.addJarsRelative(ApplicationClasspath.java:142)
>         at de.cenote.jasperstarter.App.processReport(App.java:169)
>         at de.cenote.jasperstarter.App.main(App.java:102)
> root@laravel:/var/www/mysite/vendor/cossou/jasperphp/src/JasperStarter/bin# Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
> -bash: syntax error near unexpected token `('

What should I do to further troubleshoot? Thanks.

**Comment by xIDMONx** [comment]
cambia el jdk 11 a jdk 8

**Comment by legendgod** [comment]
Thanks. By change to jdk8 the error is gone and PDF is generated.
However the pdf generated by charactersetTest.jrxml is a blank pdf page. Is it correct?

**Comment by xIDMONx** [comment]
@legendgod Y si mejor intentas generar el pdf con el archivo charactersetTest.jasper
