### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by zerogu** [cossou/JasperPHP#86]
HI,
I am running a large file, suggesting an error, Is there any solution? 
How to add -Xms and -Xmx at run time? Now:
`exec($this->the_command, $output, $return_var);`

Error information:
`Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at net.sf.jasperreports.engine.fill.JRTemplatePrintElement.getPropertiesMap(JRTemplatePrintElement.java:379)
	at net.sf.jasperreports.engine.export.MatcherExporterFilter.isToExport(MatcherExporterFilter.java:57)
	at net.sf.jasperreports.engine.export.JRXlsAbstractExporterNature.isToExport(JRXlsAbstractExporterNature.java:109)
	at net.sf.jasperreports.engine.export.ooxml.JRXlsxExporterNature.isToExport(JRXlsxExporterNature.java:75)
	at net.sf.jasperreports.engine.export.JRGridLayout.createCuts(JRGridLayout.java:305)
	at net.sf.jasperreports.engine.export.JRGridLayout.createCuts(JRGridLayout.java:319)
	at net.sf.jasperreports.engine.export.JRGridLayout.layoutGrid(JRGridLayout.java:242)
	at net.sf.jasperreports.engine.export.JRGridLayout.<init>(JRGridLayout.java:150)
	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportPage(JRXlsAbstractExporter.java:851)
	at net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter.exportPage(JRXlsxExporter.java:266)
	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReportToStream(JRXlsAbstractExporter.java:797)
	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReport(JRXlsAbstractExporter.java:674)
	at de.cenote.jasperstarter.Report.exportXlsx(Report.java:403)
	at de.cenote.jasperstarter.App.processReport(App.java:246)
	at de.cenote.jasperstarter.App.main(App.java:102)`

**Comment by cossou** [comment]
Hi @zerogu 

I believe you have to add that to your `JVM` not to script.
